// promptscript.go guards generated project instructions: the PromptScript
// CLI is pinned, source must pass strict validation, and committed outputs
// must match what the source compiles to.
package main

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
)

// pinnedPromptScriptVersion is the PromptScript CLI version this
// repository is validated against. Upgrade it deliberately: regenerate
// all generated files, review the output diff, and update the pin in the
// same change.
const pinnedPromptScriptVersion = "1.19.1"

// semverPattern matches a semantic version inside tool version output.
var semverPattern = regexp.MustCompile(`[0-9]+\.[0-9]+\.[0-9]+`)

// generatedStampPattern removes nondeterministic compile metadata while
// preserving the PromptScript source path.
var generatedStampPattern = regexp.MustCompile(
	`(?m)^# promptscript-generated: [^|\r\n]+ \| source: ([^|\r\n]+) \| target: [^\r\n]+$`,
)

// generatedCommentStampPattern handles the equivalent Markdown marker.
var generatedCommentStampPattern = regexp.MustCompile(
	`(?m)^<!-- PromptScript [^|\r\n]+ \| source: ([^|\r\n]+) \| target: [^>\r\n]+ -->$`,
)

// The OpenCode plugin is generated by PromptScript and mirrored byte for
// byte into a copyable harness template.
const (
	openCodeDir        = ".opencode"
	openCodePluginFile = "promptscript.ts"
)

var (
	openCodePluginRel   = filepath.Join(openCodeDir, "plugins", openCodePluginFile)
	openCodeTemplateRel = filepath.Join("marketplace", "harness", "opencode", openCodePluginFile)
)

const openCodePatchMarker = "// git-byline: preserve bounded file paths"

// openCodeAgentNames lists the generated OpenCode subagents. Their
// PromptScript sources grant only Read, Grep, and Glob.
var openCodeAgentNames = []string{"code-reviewer", "release-keeper", "security-reviewer"}

// PromptScript 1.19.1 writes only a description and a mode into an OpenCode
// subagent. The tools list of the source never reaches OpenCode, which would
// let a reviewer edit files and run shell commands. The patch adds a
// permission block that allows the read tools of the source and denies the
// rest.
//
// OpenCode applies the last matching rule, and an agent block lands after the
// built-in defaults. A bare "read: allow" would therefore override the default
// prompt before .env files, so the block repeats those rules after the allow.
//
// PromptScript also stamps each agent with its generation time and refreshes
// the stamp whenever the file differs from fresh output. The committed agents
// always differ by the permission block, so every compile moves the stamp and
// leaves a diff behind. The patch pins the time, which makes patched output
// the same after every compile.
const openCodeAgentStampTime = "1970-01-01T00:00:00.000Z"

var openCodeAgentStamp = regexp.MustCompile(
	`(?m)^(# promptscript-generated: )[^|\r\n]+( \| source: [^|\r\n]+ \| target: opencode)$`,
)

const (
	openCodeAgentFrontmatterEnd = "mode: subagent\n---\n"
	openCodeAgentReadOnly       = "mode: subagent\n" +
		"permission:\n" +
		"  \"*\": deny\n" +
		"  read:\n" +
		"    \"*\": allow\n" +
		"    \"*.env\": ask\n" +
		"    \"*.env.*\": ask\n" +
		"    \"*.env.example\": allow\n" +
		"  grep: allow\n" +
		"  glob: allow\n" +
		"---\n"
)

// openCodeAgentPermissionKey matches a top-level permission key. OpenCode
// parses the frontmatter as YAML, which rejects a repeated mapping key, so a
// second permission mapping next to the patch block leaves an agent that does
// not load.
var openCodeAgentPermissionKey = regexp.MustCompile(`(?m)^permission:`)

// openCodePathArguments keeps the file paths of oversized tool arguments.
// OpenCode apply_patch carries its whole patch in patchText, so the paths
// are read from the patch headers before the text is dropped.
const openCodePathArguments = `// git-byline: preserve bounded file paths
const MAX_PATH_ARGUMENT_BYTES = 2048;
const MAX_PATH_LIST_ENTRIES = 100;
const PATH_KEYS = ['filePath', 'file_path', 'file', 'path'];
const PATH_LIST_KEYS = [
  'filePaths', 'file_paths', 'editedFilepaths', 'edited_filepaths', 'files'
];
const PATCH_PATH_PATTERN = /^\*\*\* (?:Add File|Update File|Delete File|Move to): (.+)$/gm;

interface PathBudget {
  remaining: number;
}

function parseArguments(value: unknown): Record<string, unknown> {
  let args = value;
  if (typeof args === 'string') {
    try {
      args = JSON.parse(args);
    } catch {
      return {};
    }
  }
  if (args === null || typeof args !== 'object' || Array.isArray(args)) return {};
  return args as Record<string, unknown>;
}

function takePath(path: unknown, budget: PathBudget): path is string {
  if (typeof path !== 'string') return false;
  const size = payloadByteLength(path);
  if (size > budget.remaining) return false;
  budget.remaining -= size;
  return true;
}

function takePaths(paths: unknown, budget: PathBudget): string[] {
  if (!Array.isArray(paths)) return [];
  const kept: string[] = [];
  for (const path of paths.slice(0, MAX_PATH_LIST_ENTRIES)) {
    if (takePath(path, budget)) kept.push(path);
  }
  return kept;
}

function patchTextPaths(patchText: unknown): string[] {
  if (typeof patchText !== 'string') return [];
  return Array.from(patchText.matchAll(PATCH_PATH_PATTERN), (match) => match[1].trim());
}

function safePathArguments(value: unknown): Record<string, unknown> {
  const input = parseArguments(value);
  const budget: PathBudget = { remaining: MAX_PATH_ARGUMENT_BYTES };
  const safe: Record<string, unknown> = {};
  for (const key of PATH_KEYS) {
    if (takePath(input[key], budget)) safe[key] = input[key];
  }
  for (const key of PATH_LIST_KEYS) {
    const kept = takePaths(input[key], budget);
    if (kept.length > 0) safe[key] = kept;
  }
  const patched = takePaths(patchTextPaths(input.patchText), budget);
  if (patched.length > 0) {
    safe.files = [...(Array.isArray(safe.files) ? safe.files : []), ...patched];
  }
  return safe;
}

`

const openCodeTruncatedArgsLine = "const withoutArgs = { ...payload, args: '[truncated]' };"

const openCodeTruncatedFallback = `return '{"target":"opencode","args":"[truncated]","result":"[truncated]"}';`

const openCodeSafeFallback = `const minimal: Record<string, unknown> = {
    target: 'opencode',
    hook: payload.hook,
    event: payload.event,
    tool: payload.tool,
    args: {},
    timestamp: payload.timestamp
  };
  for (const key of ['sessionID', 'callID']) {
    const value = payload[key];
    if (typeof value === 'string' && payloadByteLength(value) <= 1024) {
      minimal[key] = value;
    }
  }
  return safeStringify(minimal);`

const openCodePayloadSignature = "function boundedPayload(payload: Record<string, unknown>): string {"

const openCodePayloadDoc = `// Keep the payload bounded: drop oversized tool arguments first, then the
// result object, so the command always receives parseable JSON.
`

const openCodePatchedPayloadDoc = `// Keep the payload bounded: reduce oversized tool arguments to their file
// paths first, then drop the result object, so the command always receives
// parseable JSON.
`

const openCodeRunRuleDoc = `// Hooks observe tool execution asynchronously. Failures are logged, and every
// process gets a bounded lifetime so a broken hook cannot disrupt the session.
`

const openCodePatchedRunRuleDoc = `// Hooks finish before OpenCode continues, so the pre-edit snapshot exists before
// the tool writes and the post-edit snapshot exists before the next tool starts.
// Failures are logged, and every process gets a bounded lifetime so a broken
// hook cannot disrupt the session.
`

// openCodeReplacement is one exact-match edit of the generated plugin. A
// PromptScript upgrade that changes the generated code breaks the match
// count, which fails the patch instead of leaving a half-patched plugin.
type openCodeReplacement struct {
	name   string
	before string
	after  string
	count  int
}

// openCodeReplacements turns the generated plugin into the plugin git-byline
// ships. The hooks must wait for their checkpoint: a hook that returns early
// lets OpenCode run the tool before the pre-edit snapshot is taken, which
// records the edit as human work. Each hook starts its rules in order and
// awaits them together after the loop, because an await inside the loop is a
// SonarCloud finding. The plugin factory is a plain function returning a
// promise because it has nothing to await.
var openCodeReplacements = []openCodeReplacement{
	{
		name:   "path-only arguments",
		before: openCodeTruncatedArgsLine,
		after:  "const withoutArgs = { ...payload, args: safePathArguments(payload.args) };",
		count:  1,
	},
	{
		name:   "minimal payload",
		before: openCodeTruncatedFallback,
		after:  openCodeSafeFallback,
		count:  1,
	},
	{
		name:   "payload handler",
		before: openCodePayloadDoc + openCodePayloadSignature,
		after:  openCodePathArguments + openCodePatchedPayloadDoc + openCodePayloadSignature,
		count:  1,
	},
	{
		name:   "hook runner comment",
		before: openCodeRunRuleDoc,
		after:  openCodePatchedRunRuleDoc,
		count:  1,
	},
	{
		name:   "hook run lists",
		before: "      for (const entry of compiled) {\n        if (entry.rule.event",
		after:  "      const running: Promise<void>[] = [];\n      for (const entry of compiled) {\n        if (entry.rule.event",
		count:  2,
	},
	{
		name:   "hook starts",
		before: "void runRule(",
		after:  "running.push(runRule(",
		count:  2,
	},
	{
		name:   "before hook wait",
		before: "input, output.args))\n        );\n      }\n",
		after:  "input, output.args))\n        ));\n      }\n      await Promise.all(running);\n",
		count:  1,
	},
	{
		name:   "after hook wait",
		before: "input, input.args, result))\n        );\n      }\n",
		after:  "input, input.args, result))\n        ));\n      }\n      await Promise.all(running);\n",
		count:  1,
	},
	{
		name:   "plugin factory",
		before: "export const PromptScriptHooks = async (context: OpenCodePluginContext) => {",
		after:  "export const PromptScriptHooks = (context: OpenCodePluginContext) => {",
		count:  1,
	},
	{
		name:   "hook table start",
		before: "  return {\n    'tool.execute.before'",
		after:  "  return Promise.resolve({\n    'tool.execute.before'",
		count:  1,
	},
	{
		name:   "hook table end",
		before: "    }\n  };\n};\n",
		after:  "    }\n  });\n};\n",
		count:  1,
	},
}

var promptScriptOutputs = []string{
	"AGENTS.md",
	"CLAUDE.md",
	"GEMINI.md",
	filepath.Join(".claude", "agents", "code-reviewer.md"),
	filepath.Join(".claude", "agents", "release-keeper.md"),
	filepath.Join(".claude", "agents", "security-reviewer.md"),
	filepath.Join(".claude", "settings.json"),
	filepath.Join(".claude", "workflows", "bugfix.md"),
	filepath.Join(".claude", "workflows", "feature.md"),
	filepath.Join(".claude", "workflows", "hooks.md"),
	filepath.Join(".claude", "workflows", "promptscript.md"),
	filepath.Join(".claude", "workflows", "release.md"),
	filepath.Join(".claude", "workflows", "storage.md"),
	filepath.Join(".codex", "agents", "code-reviewer.toml"),
	filepath.Join(".codex", "agents", "release-keeper.toml"),
	filepath.Join(".codex", "agents", "security-reviewer.toml"),
	filepath.Join(".codex", "config.toml"),
	filepath.Join(".codex", "hooks.json"),
	filepath.Join(".cursor", "agents", "code-reviewer.md"),
	filepath.Join(".cursor", "agents", "release-keeper.md"),
	filepath.Join(".cursor", "agents", "security-reviewer.md"),
	filepath.Join(".cursor", "hooks.json"),
	filepath.Join(".cursor", "rules", "project.mdc"),
	filepath.Join(".factory", "droids", "code-reviewer.md"),
	filepath.Join(".factory", "droids", "release-keeper.md"),
	filepath.Join(".factory", "droids", "security-reviewer.md"),
	filepath.Join(".factory", "hooks.json"),
	filepath.Join(".gemini", "settings.json"),
	filepath.Join(".github", "agents", "code-reviewer.md"),
	filepath.Join(".github", "agents", "release-keeper.md"),
	filepath.Join(".github", "agents", "security-reviewer.md"),
	filepath.Join(".github", "copilot-instructions.md"),
	filepath.Join(".github", "hooks", "promptscript-vscode.json"),
	filepath.Join(".github", "hooks", "promptscript.json"),
	filepath.Join(".grok", "hooks", "promptscript.json"),
	filepath.Join(".promptscript", "generated", "codex.md"),
	filepath.Join(".windsurf", "hooks.json"),
	filepath.Join(".windsurf", "rules", "project.md"),
	"OPENCODE.md",
	openCodeAgentRel("code-reviewer"),
	openCodeAgentRel("release-keeper"),
	openCodeAgentRel("security-reviewer"),
	openCodePluginRel,
}

// parseSemver extracts the first semantic version from text.
func parseSemver(text string) string {
	return semverPattern.FindString(text)
}

// checkPromptScript validates the PromptScript setup of the repository.
func checkPromptScript(root string) error {
	if err := requirePromptScriptFiles(root); err != nil {
		return err
	}
	bin, err := exec.LookPath("promptscript")
	if err != nil {
		return fmt.Errorf("promptscript CLI not found in PATH, pinned version %s: %w", pinnedPromptScriptVersion, err)
	}
	versionOut, err := runCapture(bin, root, "--version")
	if err != nil {
		return fmt.Errorf("promptscript --version: %w", err)
	}
	got := parseSemver(versionOut)
	if got == "" {
		return fmt.Errorf("promptscript --version output contains no version: %q", strings.TrimSpace(versionOut))
	}
	if got != pinnedPromptScriptVersion {
		return fmt.Errorf("promptscript CLI version %s does not match the pinned %s; upgrade the pin deliberately and regenerate project instructions", got, pinnedPromptScriptVersion)
	}
	if _, err := runCapture(bin, root, "validate", "--strict", ".promptscript/project.prs"); err != nil {
		return fmt.Errorf("promptscript strict validation: %w", err)
	}
	if err := checkPortableHookOutputs(root); err != nil {
		return err
	}
	return checkDrift(bin, root)
}

func checkPortableHookOutputs(root string) error {
	outputs := map[string]string{
		filepath.Join(".factory", "hooks.json"):                       "factory",
		filepath.Join(".claude", "settings.json"):                     "claude",
		filepath.Join(".github", "hooks", "promptscript.json"):        "copilot",
		filepath.Join(".github", "hooks", "promptscript-vscode.json"): "vscode",
		filepath.Join(".cursor", "hooks.json"):                        "cursor",
		filepath.Join(".codex", "hooks.json"):                         "codex",
		filepath.Join(".gemini", "settings.json"):                     "gemini",
		filepath.Join(".windsurf", "hooks.json"):                      "windsurf",
		filepath.Join(".grok", "hooks", "promptscript.json"):          "grok",
		openCodePluginRel: "opencode",
	}
	for rel, agent := range outputs {
		data, err := os.ReadFile(filepath.Join(root, rel))
		if err != nil {
			return fmt.Errorf("read generated hook output %s: %w", rel, err)
		}
		for _, author := range []string{"human", "ai"} {
			signature := fmt.Sprintf("checkpoint portable-%s --type %s", agent, author)
			if agent == "opencode" {
				signature = fmt.Sprintf(`"portable-opencode","--type","%s"`, author)
			}
			if !bytes.Contains(data, []byte(signature)) {
				return fmt.Errorf("%s is missing %s hook", rel, author)
			}
		}
		if agent == "opencode" &&
			(!bytes.Contains(data, []byte(`"tool.execute.before"`)) ||
				!bytes.Contains(data, []byte(`"tool.execute.after"`))) {
			return fmt.Errorf("%s is missing OpenCode tool hooks", rel)
		}
	}
	return nil
}

// patchOpenCodeArtifacts patches the generated OpenCode plugin in place,
// refreshes the copyable harness template from it, and restricts the
// generated subagents to reading.
func patchOpenCodeArtifacts(root string) error {
	patched, err := patchOpenCodeFile(filepath.Join(root, openCodePluginRel))
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(root, openCodeTemplateRel), patched, 0o644); err != nil {
		return fmt.Errorf("write OpenCode harness template: %w", err)
	}
	return patchOpenCodeAgents(root)
}

// openCodeAgentRel is the repository path of one generated OpenCode subagent.
func openCodeAgentRel(name string) string {
	return filepath.Join(openCodeDir, "agents", name+".md")
}

// patchOpenCodeAgents restricts every generated OpenCode subagent below root
// to the read tools.
func patchOpenCodeAgents(root string) error {
	for _, name := range openCodeAgentNames {
		path := filepath.Join(root, openCodeAgentRel(name))
		agent, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read generated OpenCode agent %s: %w", name, err)
		}
		patched, err := patchOpenCodeAgent(agent)
		if err != nil {
			return fmt.Errorf("patch generated OpenCode agent %s: %w", name, err)
		}
		if err := os.WriteFile(path, patched, 0o644); err != nil {
			return fmt.Errorf("write generated OpenCode agent %s: %w", name, err)
		}
	}
	return nil
}

// patchOpenCodeAgent adds the read-only permission block to one generated
// subagent and pins the generation time of its stamp. An agent that already
// carries the block keeps it, so patching twice is safe. Any other frontmatter
// shape fails instead of guessing, which points a PromptScript upgrade at this
// patch. That includes a permission mapping of its own, whether PromptScript
// writes one in a later version or someone adds one by hand. A missing stamp
// is fine: only the timestamp is pinned.
func patchOpenCodeAgent(data []byte) ([]byte, error) {
	text := string(data)
	if !strings.Contains(text, openCodeAgentReadOnly) {
		if got := strings.Count(text, openCodeAgentFrontmatterEnd); got != 1 {
			return nil, fmt.Errorf("generated OpenCode agent has %d matches for the frontmatter end, want 1", got)
		}
		text = strings.Replace(text, openCodeAgentFrontmatterEnd, openCodeAgentReadOnly, 1)
	}
	// The block closes the frontmatter, so the text before it is the rest of
	// the frontmatter. The body below the block is free text.
	if openCodeAgentPermissionKey.MatchString(text[:strings.Index(text, openCodeAgentReadOnly)]) {
		return nil, errors.New("generated OpenCode agent has a permission mapping besides the read-only block")
	}
	return openCodeAgentStamp.ReplaceAll(
		[]byte(text),
		[]byte("${1}"+openCodeAgentStampTime+"${2}"),
	), nil
}

// patchOpenCodeFile applies the repository patch to the generated plugin at
// path and returns the patched content.
func patchOpenCodeFile(path string) ([]byte, error) {
	plugin, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read generated OpenCode plugin: %w", err)
	}
	patched, err := patchOpenCodePlugin(plugin)
	if err != nil {
		return nil, fmt.Errorf("patch generated OpenCode plugin: %w", err)
	}
	if err := os.WriteFile(path, patched, 0o644); err != nil {
		return nil, fmt.Errorf("write generated OpenCode plugin: %w", err)
	}
	return patched, nil
}

// hasUnpatchedCode reports whether the code that an edit replaces is still in
// text outside the edit's result. The result of "hook run lists" contains the
// code it replaces, so every result is masked before the search. Without the
// mask, a correctly patched plugin would count as unpatched.
func hasUnpatchedCode(text string, edit openCodeReplacement) bool {
	return strings.Contains(strings.ReplaceAll(text, edit.after, "\x00"), edit.before)
}

// patchOpenCodePlugin applies openCodeReplacements to freshly generated
// plugin code. A plugin that already carries the patch is verified and
// returned unchanged, so patching twice is safe. Verifying means every edit
// is present and none of the replaced code is left, which rejects a plugin
// that was regenerated or edited only in part.
func patchOpenCodePlugin(data []byte) ([]byte, error) {
	text := string(data)
	if strings.Contains(text, openCodePatchMarker) {
		for _, edit := range openCodeReplacements {
			if strings.Count(text, edit.after) < edit.count {
				return nil, fmt.Errorf("patched OpenCode plugin is missing the %s patch", edit.name)
			}
			if hasUnpatchedCode(text, edit) {
				return nil, fmt.Errorf("patched OpenCode plugin still has unpatched %s code", edit.name)
			}
		}
		return data, nil
	}
	for _, edit := range openCodeReplacements {
		if got := strings.Count(text, edit.before); got != edit.count {
			return nil, fmt.Errorf("generated OpenCode plugin has %d matches for the %s code, want %d",
				got, edit.name, edit.count)
		}
	}
	for _, edit := range openCodeReplacements {
		text = strings.ReplaceAll(text, edit.before, edit.after)
	}
	return []byte(text), nil
}

// requirePromptScriptFiles verifies the source and config exist.
func requirePromptScriptFiles(root string) error {
	for _, rel := range []string{
		filepath.Join(".promptscript", "project.prs"),
		"promptscript.yaml",
	} {
		if _, err := os.Stat(filepath.Join(root, rel)); err != nil {
			return fmt.Errorf("promptscript file %s missing: %w", rel, err)
		}
	}
	return nil
}

// checkDrift compiles PromptScript source in an isolated copy and compares
// all outputs with committed files. The copy keeps the repository untouched
// even when a committed file has drifted.
func checkDrift(bin, root string) error {
	tmp, err := os.MkdirTemp("", "byline-drift-")
	if err != nil {
		return fmt.Errorf("create temp dir: %w", err)
	}
	defer os.RemoveAll(tmp)

	srcDir := filepath.Join(tmp, ".promptscript")
	if err := os.MkdirAll(srcDir, 0o755); err != nil {
		return fmt.Errorf("create %s: %w", srcDir, err)
	}
	entries, err := os.ReadDir(filepath.Join(root, ".promptscript"))
	if err != nil {
		return fmt.Errorf("read PromptScript source directory: %w", err)
	}
	files := []struct{ src, dst string }{
		{filepath.Join(root, "promptscript.yaml"), filepath.Join(tmp, "promptscript.yaml")},
	}
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".prs" {
			continue
		}
		files = append(files, struct{ src, dst string }{
			src: filepath.Join(root, ".promptscript", entry.Name()),
			dst: filepath.Join(srcDir, entry.Name()),
		})
	}
	for _, f := range files {
		data, err := os.ReadFile(f.src)
		if err != nil {
			return fmt.Errorf("read %s: %w", f.src, err)
		}
		if err := os.WriteFile(f.dst, data, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", f.dst, err)
		}
	}
	if _, err := runCapture(bin, tmp, "compile", "--all-builds", "--force", "--strict"); err != nil {
		return fmt.Errorf("compile build profiles in isolated copy: %w", err)
	}
	if _, err := runCapture(bin, tmp, "compile", "--all", "--force", "--strict"); err != nil {
		return fmt.Errorf("compile targets in isolated copy: %w", err)
	}
	compiled, err := compiledOutputPaths(tmp)
	if err != nil {
		return err
	}
	expected := make(map[string]bool, len(promptScriptOutputs))
	for _, rel := range promptScriptOutputs {
		expected[filepath.Clean(rel)] = true
	}
	for _, rel := range compiled {
		if !expected[rel] {
			return fmt.Errorf("untracked PromptScript output %s; add it to promptScriptOutputs", rel)
		}
	}
	// Committed files hold the patched plugin and agents, so compare against
	// the same.
	if _, err := patchOpenCodeFile(filepath.Join(tmp, openCodePluginRel)); err != nil {
		return err
	}
	if err := patchOpenCodeAgents(tmp); err != nil {
		return err
	}
	for _, rel := range promptScriptOutputs {
		generated, err := os.ReadFile(filepath.Join(tmp, rel))
		if err != nil {
			return fmt.Errorf("read generated %s: %w", rel, err)
		}
		committed, err := os.ReadFile(filepath.Join(root, rel))
		if err != nil {
			return fmt.Errorf("read committed %s: %w", rel, err)
		}
		generated = normalizeGeneratedStamps(generated)
		committed = normalizeGeneratedStamps(committed)
		if !bytes.Equal(generated, committed) {
			return fmt.Errorf(
				"%s is out of sync with .promptscript sources; run all build profiles, then all targets",
				rel,
			)
		}
	}
	return nil
}

func compiledOutputPaths(root string) ([]string, error) {
	var outputs []string
	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		if rel == "promptscript.yaml" ||
			strings.HasPrefix(rel, ".promptscript"+string(filepath.Separator)) &&
				filepath.Ext(rel) == ".prs" {
			return nil
		}
		outputs = append(outputs, filepath.Clean(rel))
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("list compiled PromptScript outputs: %w", err)
	}
	return outputs, nil
}

func normalizeGeneratedStamps(data []byte) []byte {
	data = generatedStampPattern.ReplaceAll(
		data,
		[]byte("# promptscript-generated: <generated> | source: $1 | target: <target>"),
	)
	return generatedCommentStampPattern.ReplaceAll(
		data,
		[]byte("<!-- PromptScript <generated> | source: $1 | target: <target> -->"),
	)
}

// runCapture runs a command in dir, capturing combined output, and wraps
// failures with that output.
func runCapture(bin, dir string, args ...string) (string, error) {
	cmd := exec.Command(bin, args...)
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "NO_COLOR=1")
	out, err := cmd.CombinedOutput()
	if err != nil {
		return string(out), fmt.Errorf("%s %s: %w\n%s", filepath.Base(bin), strings.Join(args, " "), err, out)
	}
	return string(out), nil
}
