// promptscript-generated: opencode-plugin
// Generated by PromptScript - do not edit.
// Recompiling the .promptscript sources rewrites this file; manual edits are discarded.
// Scope: OpenCode fires these hooks for local tool executions only. MCP tool calls,
// some subagent paths, and failed tool calls have no dedicated plugin hook.
// OpenCode tool hooks do not expose model or agent context; payloads omit those fields.

interface OpenCodeHookRule {
  id: string;
  event: 'tool.execute.before' | 'tool.execute.after';
  matcher?: string;
  command: string[];
  cwd?: string;
  timeoutMs?: number;
}

const HOOK_RULES: readonly OpenCodeHookRule[] = [
  {"id":"opencode-pre-edit","event":"tool.execute.before","matcher":"^(edit|write)$","command":["git-byline","checkpoint","portable-opencode","--type","human","--hook-input","stdin"],"timeoutMs":30000},
  {"id":"opencode-post-edit","event":"tool.execute.after","matcher":"^(edit|write)$","command":["git-byline","checkpoint","portable-opencode","--type","ai","--hook-input","stdin"],"timeoutMs":30000},
  {"id":"opencode-shell-pre","event":"tool.execute.before","matcher":"^bash$","command":["git-byline","checkpoint","portable-opencode","--type","human","--hook-input","stdin"],"timeoutMs":30000},
  {"id":"opencode-shell-post","event":"tool.execute.after","matcher":"^bash$","command":["git-byline","checkpoint","portable-opencode","--type","ai","--hook-input","stdin"],"timeoutMs":30000}
];

const PAYLOAD_LIMIT_BYTES = 32768;
const DEFAULT_TIMEOUT_MS = 30000;
const KILL_GRACE_MS = 1000;

interface OpenCodePluginContext {
  directory: string;
  worktree?: string;
}

interface OpenCodeToolInput {
  tool?: string;
  sessionID?: string;
  callID?: string;
  args?: unknown;
}

interface OpenCodeToolOutput {
  args?: unknown;
}

interface OpenCodeToolResult {
  title?: unknown;
  output?: unknown;
  metadata?: unknown;
}

interface OpenCodeCompiledRule {
  rule: OpenCodeHookRule;
  matcher: RegExp | null;
}

function safeStringify(value: unknown): string {
  try {
    return JSON.stringify(value);
  } catch {
    return '{}';
  }
}

function payloadByteLength(value: string): number {
  return new TextEncoder().encode(value).byteLength;
}

// Keep the payload bounded: drop oversized tool arguments first, then the
// result object, so the command always receives parseable JSON.
// git-byline: preserve bounded file paths
const MAX_PATH_ARGUMENT_BYTES = 2048;

function safePathArguments(value: unknown): Record<string, unknown> {
  let args = value;
  if (typeof args === 'string') {
    try {
      args = JSON.parse(args);
    } catch {
      return {};
    }
  }
  if (args === null || typeof args !== 'object' || Array.isArray(args)) return {};
  const input = args as Record<string, unknown>;
  const safe: Record<string, unknown> = {};
  let remaining = MAX_PATH_ARGUMENT_BYTES;
  const keepPath = (path: unknown): path is string => {
    if (typeof path !== 'string') return false;
    const size = payloadByteLength(path);
    if (size > remaining) return false;
    remaining -= size;
    return true;
  };
  for (const key of ['filePath', 'file_path', 'file', 'path']) {
    const path = input[key];
    if (keepPath(path)) safe[key] = path;
  }
  for (const key of [
    'filePaths', 'file_paths', 'editedFilepaths', 'edited_filepaths', 'files'
  ]) {
    const paths = input[key];
    if (!Array.isArray(paths)) continue;
    const kept: string[] = [];
    for (const path of paths.slice(0, 100)) {
      if (keepPath(path)) kept.push(path);
    }
    if (kept.length > 0) safe[key] = kept;
  }
  return safe;
}

function boundedPayload(payload: Record<string, unknown>): string {
  const full = safeStringify(payload);
  if (payloadByteLength(full) <= PAYLOAD_LIMIT_BYTES) return full;
  const withoutArgs = { ...payload, args: safePathArguments(payload.args) };
  const trimmed = safeStringify(withoutArgs);
  if (payloadByteLength(trimmed) <= PAYLOAD_LIMIT_BYTES) return trimmed;
  const withoutResult = safeStringify({ ...withoutArgs, result: '[truncated]' });
  if (payloadByteLength(withoutResult) <= PAYLOAD_LIMIT_BYTES) return withoutResult;
  const minimal: Record<string, unknown> = {
    target: 'opencode',
    hook: payload.hook,
    event: payload.event,
    tool: payload.tool,
    args: {},
    timestamp: payload.timestamp
  };
  for (const key of ['sessionID', 'callID']) {
    const value = payload[key];
    if (typeof value === 'string' && payloadByteLength(value) <= 1024) {
      minimal[key] = value;
    }
  }
  return safeStringify(minimal);
}

function buildPayload(
  rule: OpenCodeHookRule,
  input: OpenCodeToolInput,
  args: unknown,
  result?: unknown
): Record<string, unknown> {
  const payload: Record<string, unknown> = {
    target: 'opencode',
    hook: rule.id,
    event: rule.event === 'tool.execute.before' ? 'pre-tool-use' : 'post-tool-use',
    tool: input.tool,
    args,
    sessionID: input.sessionID,
    callID: input.callID,
    timestamp: new Date().toISOString()
  };
  if (result !== undefined) payload.result = result;
  return payload;
}

// Hooks observe tool execution asynchronously. Failures are logged, and every
// process gets a bounded lifetime so a broken hook cannot disrupt the session.
async function runRule(
  rule: OpenCodeHookRule,
  projectRoot: string,
  payload: string
): Promise<void> {
  try {
    const cwd = rule.cwd ? projectRoot + '/' + rule.cwd : projectRoot;
    const proc = Bun.spawn({
      cmd: rule.command,
      cwd,
      stdin: 'pipe',
      stdout: 'inherit',
      stderr: 'inherit'
    });
    const timeoutMs = rule.timeoutMs ?? DEFAULT_TIMEOUT_MS;
    let graceTimer: ReturnType<typeof setTimeout> | undefined;
    const timer = setTimeout(() => {
      proc.kill('SIGTERM');
      graceTimer = setTimeout(() => proc.kill('SIGKILL'), KILL_GRACE_MS);
    }, timeoutMs);
    try {
      proc.stdin.write(payload);
      proc.stdin.end();
      const exitCode = await proc.exited;
      if (exitCode !== 0) {
        console.error(
          '[promptscript] opencode hook "' + rule.id + '" exited with code ' + exitCode
        );
      }
    } finally {
      clearTimeout(timer);
      if (graceTimer !== undefined) clearTimeout(graceTimer);
    }
  } catch (error: unknown) {
    console.error('[promptscript] opencode hook "' + rule.id + '" failed:', error);
  }
}

export const PromptScriptHooks = async (context: OpenCodePluginContext) => {
  const projectRoot = context.worktree || context.directory;
  const compiled: OpenCodeCompiledRule[] = [];
  for (const rule of HOOK_RULES) {
    if (rule.matcher === undefined) {
      compiled.push({ rule, matcher: null });
      continue;
    }
    try {
      compiled.push({ rule, matcher: new RegExp(rule.matcher) });
    } catch (error: unknown) {
      console.error(
        '[promptscript] opencode hook "' + rule.id + '" has an invalid matcher:',
        rule.matcher
      );
    }
  }

  return {
    'tool.execute.before': async (input: OpenCodeToolInput, output: OpenCodeToolOutput) => {
      for (const entry of compiled) {
        if (entry.rule.event !== 'tool.execute.before') continue;
        if (entry.matcher !== null && !entry.matcher.test(String(input.tool))) continue;
        void runRule(
          entry.rule,
          projectRoot,
          boundedPayload(buildPayload(entry.rule, input, output.args))
        );
      }
    },
    'tool.execute.after': async (input: OpenCodeToolInput, output: OpenCodeToolResult) => {
      for (const entry of compiled) {
        if (entry.rule.event !== 'tool.execute.after') continue;
        if (entry.matcher !== null && !entry.matcher.test(String(input.tool))) continue;
        const result = {
          title: output.title,
          output: output.output,
          metadata: output.metadata
        };
        void runRule(
          entry.rule,
          projectRoot,
          boundedPayload(buildPayload(entry.rule, input, input.args, result))
        );
      }
    }
  };
};
